<div style="color:white;
            display:fill;
            border-radius:15px;
            background-color:purple;
            font-size:100%;
            font-family:Verdana;
            letter-spacing:1px">
    <h3 style='padding: 20px;
              color:white;
              text-align:center;'>
        IMPORTING LIBRARIES
    </h3>
    </div>

In [37]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

<div style="color:white;
            display:fill;
            border-radius:15px;
            background-color:purple;
            font-size:100%;
            font-family:Verdana;
            letter-spacing:1px">
    <h3 style='padding: 20px;
              color:white;
              text-align:center;'>
        IMPORTING DATA
    </h3>
    </div>

In [38]:
data = pd.read_csv('app_status -.csv')

<div style="color:white;
            display:fill;
            border-radius:15px;
            background-color:purple;
            font-size:100%;
            font-family:Verdana;
            letter-spacing:1px">
    <h3 style='padding: 20px;
              color:white;
              text-align:center;'>
        READING DATA
    </h3>
    </div>

In [39]:
data

         os app_version  failed_count
0   ANDROID        2.62          2711
1       IOS      2.6.31          1403
2   ANDROID        2.59          1345
3       IOS      2.6.30           452
4       IOS      2.6.10           201
5       IOS      2.6.27           169
6       NaN        2.59           143
7       NaN      2.6.30            98
8       NaN        2.62            73
9       NaN      2.6.10            67
10      IOS      2.6.26            54
11  ANDROID        2.57            47
12      NaN      2.6.27            19
13  ANDROID        2.41            14
14      IOS       2.4.1            14
15  ANDROID        2.53             9
16  ANDROID        2.52             7
17      IOS       2.6.8             5
18      NaN      2.6.26             5
19      NaN      2.6.29             5
20      IOS       2.2.5             4
21      NaN        2.60             4
22      IOS      2.6.22             3
23      IOS      2.6.24             3
24  ANDROID        2.51             2
25      NaN        2.58             2
26      IOS      2.6.25             2
27      IOS      2.6.21             2
28      IOS       2.5.5             2
29      NaN        2.57             2
30  ANDROID        2.58             1
31      IOS       2.6.6             1
32      NaN       2.2.5             1

In [40]:
print("The size of this data is " + str(data.size)+".")
print("There are "+str(data.shape[0])+" rows and "+str(data.shape[1])+" columns in this data.")

The size of this data is 99.
There are 33 rows and 3 columns in this data.

In [41]:
# Checking Null Values in Our Data
data.isnull().sum()

os              11
app_version      0
failed_count     0
dtype: int64

In [42]:
# The names of all 13 columns are defined below
data.columns

Index(['os', 'app_version', 'failed_count'], dtype='str')

In [43]:
# Describe method automatically performs operations on data and shows count,mean,standard deviation,min,max and etc.
print(data.describe())

       failed_count
count     33.000000
mean     208.181818
std      559.465228
min        1.000000
25%        2.000000
50%        7.000000
75%       73.000000
max     2711.000000

<div style="color:white;
            display:fill;
            border-radius:15px;
            background-color:purple;
            font-size:100%;
            font-family:Verdana;
            letter-spacing:1px">
    <h3 style='padding: 20px;
              color:white;
              text-align:center;'>
        DATA CLEANING
    </h3>
    </div>

In [44]:
data

         os app_version  failed_count
0   ANDROID        2.62          2711
1       IOS      2.6.31          1403
2   ANDROID        2.59          1345
3       IOS      2.6.30           452
4       IOS      2.6.10           201
5       IOS      2.6.27           169
6       NaN        2.59           143
7       NaN      2.6.30            98
8       NaN        2.62            73
9       NaN      2.6.10            67
10      IOS      2.6.26            54
11  ANDROID        2.57            47
12      NaN      2.6.27            19
13  ANDROID        2.41            14
14      IOS       2.4.1            14
15  ANDROID        2.53             9
16  ANDROID        2.52             7
17      IOS       2.6.8             5
18      NaN      2.6.26             5
19      NaN      2.6.29             5
20      IOS       2.2.5             4
21      NaN        2.60             4
22      IOS      2.6.22             3
23      IOS      2.6.24             3
24  ANDROID        2.51             2
25      NaN        2.58             2
26      IOS      2.6.25             2
27      IOS      2.6.21             2
28      IOS       2.5.5             2
29      NaN        2.57             2
30  ANDROID        2.58             1
31      IOS       2.6.6             1
32      NaN       2.2.5             1

In [45]:
# filling null values with avg number of os

avgos= data.groupby('app_version')['os'].unique()
avgos

app_version
2.2.5         [IOS, nan]
2.4.1              [IOS]
2.41           [ANDROID]
2.5.5              [IOS]
2.51           [ANDROID]
2.52           [ANDROID]
2.53           [ANDROID]
2.57      [ANDROID, nan]
2.58      [nan, ANDROID]
2.59      [ANDROID, nan]
2.6.10        [IOS, nan]
2.6.21             [IOS]
2.6.22             [IOS]
2.6.24             [IOS]
2.6.25             [IOS]
2.6.26        [IOS, nan]
2.6.27        [IOS, nan]
2.6.29             [nan]
2.6.30        [IOS, nan]
2.6.31             [IOS]
2.6.6              [IOS]
2.6.8              [IOS]
2.60               [nan]
2.62      [ANDROID, nan]
Name: os, dtype: object

In [51]:
filled = data.dropna(subset=['os']).drop_duplicates('app_version').set_index('app_version')['os'].to_dict()
filled

{'2.62': 'ANDROID',
 '2.6.31': 'IOS',
 '2.59': 'ANDROID',
 '2.6.30': 'IOS',
 '2.6.10': 'IOS',
 '2.6.27': 'IOS',
 '2.6.26': 'IOS',
 '2.57': 'ANDROID',
 '2.41': 'ANDROID',
 '2.4.1': 'IOS',
 '2.53': 'ANDROID',
 '2.52': 'ANDROID',
 '2.6.8': 'IOS',
 '2.2.5': 'IOS',
 '2.6.22': 'IOS',
 '2.6.24': 'IOS',
 '2.51': 'ANDROID',
 '2.58': 'ANDROID',
 '2.6.25': 'IOS',
 '2.6.21': 'IOS',
 '2.5.5': 'IOS',
 '2.6.6': 'IOS'}

In [50]:
# 2. Sirf NaN values fill karo
data['os'] = data['os'].fillna(data['app_version'].map(filled))

data.isnull().sum()

os              2
app_version     0
failed_count    0
dtype: int64

In [52]:
data[data['os'].isna()][['os', 'app_version']]

     os app_version
19  NaN      2.6.29
21  NaN        2.60

In [53]:
print(data.loc[data['app_version'].isna(), 'app_version'].tolist())

[]

In [55]:
data.dropna(subset=['os'],inplace=True)
data

         os app_version  failed_count
0   ANDROID        2.62          2711
1       IOS      2.6.31          1403
2   ANDROID        2.59          1345
3       IOS      2.6.30           452
4       IOS      2.6.10           201
5       IOS      2.6.27           169
6   ANDROID        2.59           143
7       IOS      2.6.30            98
8   ANDROID        2.62            73
9       IOS      2.6.10            67
10      IOS      2.6.26            54
11  ANDROID        2.57            47
12      IOS      2.6.27            19
13  ANDROID        2.41            14
14      IOS       2.4.1            14
15  ANDROID        2.53             9
16  ANDROID        2.52             7
17      IOS       2.6.8             5
18      IOS      2.6.26             5
20      IOS       2.2.5             4
22      IOS      2.6.22             3
23      IOS      2.6.24             3
24  ANDROID        2.51             2
25  ANDROID        2.58             2
26      IOS      2.6.25             2
27      IOS      2.6.21             2
28      IOS       2.5.5             2
29  ANDROID        2.57             2
30  ANDROID        2.58             1
31      IOS       2.6.6             1
32      IOS       2.2.5             1

In [56]:
data.to_csv(r"C:\Users\Admin\Desktop\apps analysis\app_status -.csv" , index=False)

<div style="color:white;
            display:fill;
            border-radius:15px;
            background-color:purple;
            font-size:100%;
            font-family:Verdana;
            letter-spacing:1px">
    <h3 style='padding: 20px;
              color:white;
              text-align:center;'>
        EDA
    </h3>
    </div>

<div style="color:white;
            display:fill;
            border-radius:15px;
            background-color:purple;
            font-size:100%;
            font-family:Verdana;
            letter-spacing:1px">
    <h3 style='padding: 20px;
              color:white;
              text-align:center;'>
    Thanks For Reading My Notebook!
    </h3>
    </div>